In [1]:
"""- 2. Gestión sistemas de inventario de una tienda
    
    **Objetivo:** Utilizar arrays en `NumPy` para gestionar y analizar un sistema de inventario de una tienda. Practicarás la creación de arrays de diferentes dimensiones y tipos, y manipularás datos relacionados con los productos de una tienda.
    
    **Escenario:** Imagina que eres el encargado de gestionar el inventario de una tienda de electrónica. La tienda tiene diferentes productos, y necesitas hacer un seguimiento de las cantidades disponibles, los precios y las categorías de productos. Utilizarás `NumPy` para organizar esta información.
    
    ### Tareas:
    
    1. **Crear un array unidimensional con el nombre de los productos:** Tienes una lista de 5 productos: `"Smartphone"`, `"Tablet"`, `"Laptop"`, `"Auriculares"`, `"Teclado"`. Imprímelo.
    2. **Crear un array bidimensional con la cantidad en stock de cada producto:** La tienda tiene el siguiente stock de productos:
        
        ```bash
        Smartphone - 50
        Tablet - 30
        Laptop - 15
        Auriculares - 40
        Teclado - 60
        ```
        
        Crea un array bidimensional donde cada fila represente un producto y las columnas representen el stock disponible en diferentes almacenes. Imprime el array.
        
    3. **Crear un array tridimensional para registrar las ventas de cada producto durante una semana:** Imagina que tienes un registro de ventas para cada uno de los 5 productos durante 3 días de la semana. Cada capa del array representará un día de ventas y las columnas serán las cantidades vendidas para cada producto:
        
        ```bash
        Día 1: [5, 3, 2, 6, 4]
        Día 2: [7, 4, 1, 8, 5]
        Día 3: [6, 2, 3, 5, 4]
        ```
        
        Crea un array tridimensional que almacene esta información. Imprímelo.
        
    4. **Crear un array de ceros para los productos no vendidos hoy:** Los productos que no se han vendido hoy deben estar en cero. Crea un array de ceros para representar la cantidad de productos no vendidos de la tienda hoy. Imprime el array.
    5. **Crear un array de unos para los productos que están en promoción:** Los productos en promoción tienen un valor de `1`, mientras que los que no están en promoción tienen `0`. Crea un array de unos y ceros, donde los productos en promoción tienen el valor `1`. Los productos en promoción son el `"Smartphone"` y el `"Teclado"`. Imprímelo.
    6. **Crear un array con un rango de precios de productos:** La tienda tiene productos cuyo precio varía entre 50 y 1000 unidades monetarias. Crea un array con los precios de los productos, usando la función `np.arange`, y un paso de 50 unidades. Imprímelo.
    7. **Crear un array de precios aleatorios:** Crea un array con precios aleatorios para los productos entre 100 y 500 unidades monetarias, de tamaño 5. Imprímelo.
    8. **Generar un array de números enteros aleatorios para la cantidad vendida:** Utiliza `np.random.randint` para crear un array de 5 elementos, con valores aleatorios entre 1 y 10, que representen las unidades vendidas de cada producto hoy. Imprímelo.
    9. **Crear un array vacío para almacenar los valores de descuento:** Crea un array vacío de tamaño 5x1 para almacenar los descuentos que se aplicarán a cada producto. Imprímelo.
    10. **Generar un array con valores espaciados para analizar el cambio en las ventas:** Imagina que deseas analizar cómo cambian las ventas en diferentes intervalos de tiempo (por ejemplo, cada 2 horas). Utiliza `np.linspace`para generar un array con 5 puntos de venta, distribuidos entre 0 y 1000 unidades, representando las ventas totales del día. Imprímelo."""

import numpy as np

# --- Tarea 1: Crear un array unidimensional con el nombre de los productos ---
# Lista de nombres de productos disponibles en la tienda.
productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"])
print("Productos disponibles en la tienda:")
print(productos)

# --- Tarea 2: Crear un array bidimensional con el stock de cada producto ---
# El stock en diferentes almacenes está organizado en filas (productos) y columnas (almacenes).
stock = np.array([
    [50, 30, 20],  # Stock del Smartphone en 3 almacenes
    [30, 25, 15],  # Stock de la Tablet
    [15, 10, 5],   # Stock de la Laptop
    [40, 35, 25],  # Stock de los Auriculares
    [60, 50, 40]   # Stock del Teclado
])
print("\nStock de productos en almacenes:")
print(stock)

# --- Tarea 3: Crear un array tridimensional para registrar las ventas de cada producto durante la semana ---
# Registro de ventas para 3 días (capa del array) de los productos en la tienda.
ventas = np.array([
    [5, 3, 2, 6, 4],  # Ventas del día 1
    [7, 4, 1, 8, 5],  # Ventas del día 2
    [6, 2, 3, 5, 4]   # Ventas del día 3
])
print("\nVentas de productos durante la semana:")
print(ventas)

# --- Tarea 4: Crear un array de ceros para los productos no vendidos hoy ---
# Este array representa la cantidad de productos no vendidos (todo inicializado en cero).
productos_no_vendidos = np.zeros(5)
print("\nProductos no vendidos hoy:")
print(productos_no_vendidos)

# --- Tarea 5: Crear un array de unos para los productos en promoción ---
# Los productos en promoción tienen un valor de 1.
# Smartphone (índice 0) y Teclado (índice 4) están en promoción.
promociones = np.array([1, 0, 0, 0, 1])
print("\nProductos en promoción (1 = en promoción, 0 = no):")
print(promociones)

# --- Tarea 6: Crear un array con un rango de precios de productos ---
# Usamos np.arange para generar precios desde 50 hasta 1000, con un paso de 50.
precios_rango = np.arange(50, 1050, 50)
print("\nRango de precios de productos:")
print(precios_rango)

# --- Tarea 7: Crear un array de precios aleatorios ---
# Generamos precios aleatorios entre 100 y 500 para los 5 productos.
precios_aleatorios = np.random.uniform(100, 500, 5)
print("\nPrecios aleatorios de los productos:")
print(precios_aleatorios)

# --- Tarea 8: Generar un array de números enteros aleatorios para la cantidad vendida ---
# Creamos un array con valores enteros aleatorios entre 1 y 10 para representar ventas del día.
unidades_vendidas = np.random.randint(1, 11, 5)
print("\nUnidades vendidas de cada producto hoy:")
print(unidades_vendidas)

# --- Tarea 9: Crear un array vacío para almacenar los valores de descuento ---
# Array vacío para los descuentos que se aplicarán a cada producto (5 productos).
descuentos = np.empty((5, 1))
print("\nArray vacío para los valores de descuento:")
print(descuentos)

# --- Tarea 10: Generar un array con valores espaciados para analizar el cambio en las ventas ---
# Usamos np.linspace para generar 5 puntos de ventas totales distribuidos entre 0 y 1000.
ventas_totales = np.linspace(0, 1000, 5)
print("\nDistribución de las ventas totales del día:")
print(ventas_totales)


Productos disponibles en la tienda:
['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']

Stock de productos en almacenes:
[[50 30 20]
 [30 25 15]
 [15 10  5]
 [40 35 25]
 [60 50 40]]

Ventas de productos durante la semana:
[[5 3 2 6 4]
 [7 4 1 8 5]
 [6 2 3 5 4]]

Productos no vendidos hoy:
[0. 0. 0. 0. 0.]

Productos en promoción (1 = en promoción, 0 = no):
[1 0 0 0 1]

Rango de precios de productos:
[  50  100  150  200  250  300  350  400  450  500  550  600  650  700
  750  800  850  900  950 1000]

Precios aleatorios de los productos:
[240.13024044 316.75530636 446.91317317 445.36993442 493.96529287]

Unidades vendidas de cada producto hoy:
[ 4  2  3  8 10]

Array vacío para los valores de descuento:
[[240.13024044]
 [316.75530636]
 [446.91317317]
 [445.36993442]
 [493.96529287]]

Distribución de las ventas totales del día:
[   0.  250.  500.  750. 1000.]


In [ ]:
"""- 3. Indexación y selección en arrays con Numpy
    
    En este ejercicio, trabajarás con arrays 1D y 2D en NumPy, aplicando indexación y selección de elementos.
    
    ### Tareas:
    
    1. **Creación de arrays**
        - Crea un array **1D** con los números del **1 al 10** utilizando `np.arange()`.
        - Crea un array **2D** de tamaño **3x3** con valores del **1 al 9** utilizando `np.arange()` y `.reshape()`.
    2. **Indexación en arrays**
        - Extrae y muestra:
            - El primer y último elemento del array 1D.
            - El primer elemento de la primera fila del array 2D.
            - El último elemento de la última fila del array 2D.
            - El elemento ubicado en la segunda fila y tercera columna del array 2D.
    3. **Selección de filas y columnas**
        - Extrae y muestra:
            - La primera fila completa del array 2D.
            - La segunda columna completa del array 2D."""

# --- Tarea 1: Creación de arrays ---

# Creamos un array 1D con los números del 1 al 10 utilizando np.arange()
array_1d = np.arange(1, 11)
print("Array 1D:")
print(array_1d)

# Creamos un array 2D de tamaño 3x3 con valores del 1 al 9 utilizando np.arange() y .reshape()
array_2d = np.arange(1, 10).reshape(3, 3)
print("\nArray 2D:")
print(array_2d)

# --- Tarea 2: Indexación en arrays ---

# Extraemos y mostramos el primer y último elemento del array 1D
primer_elemento_1d = array_1d[0]  # Índice 0 para el primer elemento
ultimo_elemento_1d = array_1d[-1]  # Índice -1 para el último elemento
print("\nPrimer elemento del array 1D:", primer_elemento_1d)
print("Último elemento del array 1D:", ultimo_elemento_1d)

# Extraemos y mostramos el primer elemento de la primera fila del array 2D
primer_elemento_2d = array_2d[0, 0]  # Fila 0, Columna 0
print("\nPrimer elemento de la primera fila del array 2D:", primer_elemento_2d)

# Extraemos y mostramos el último elemento de la última fila del array 2D
ultimo_elemento_2d = array_2d[-1, -1]  # Última fila (-1), Última columna (-1)
print("Último elemento de la última fila del array 2D:", ultimo_elemento_2d)

# Extraemos y mostramos el elemento ubicado en la segunda fila y tercera columna del array 2D
elemento_segunda_fila_tercera_columna = array_2d[1, 2]  # Fila 1, Columna 2 (indexación comienza en 0)
print("Elemento en la segunda fila y tercera columna del array 2D:", elemento_segunda_fila_tercera_columna)

# --- Tarea 3: Selección de filas y columnas ---

# Extraemos y mostramos la primera fila completa del array 2D
primera_fila = array_2d[0, :]  # Fila 0, todas las columnas (:)
print("\nPrimera fila completa del array 2D:", primera_fila)

# Extraemos y mostramos la segunda columna completa del array 2D
segunda_columna = array_2d[:, 1]  # Todas las filas (:), Columna 1
print("Segunda columna completa del array 2D:", segunda_columna)



In [ ]:
"""- 4. Explorando una imagen en formato de Array 3D
    
    En este ejercicio, simularemos una imagen representada como un **array 3D** en NumPy. En procesamiento de imágenes, un array 3D suele representar una imagen con dimensiones `(altura, anchura, canales)`, donde los **canales** pueden ser **rojo (R), verde (G) y azul (B)** en imágenes a color.
    
    ### Tareas:
    
    1. **Creación del array 3D**
        - Genera un array 3D de tamaño **4x4x3** con valores aleatorios entre **0 y 255** para simular una imagen en formato RGB.
        - Usa `np.random.randint()` para generar valores enteros.
    2. **Indexación en el array 3D**
        - Extrae y muestra:
            - El primer píxel (posición `[0,0]`) con sus valores de color **(R, G, B)**.
            - El último píxel de la imagen (posición `[-1,-1]`).
            - El valor del canal rojo del píxel en la segunda fila y tercera columna.
    3. **Slicing en el array 3D**
        - Extrae y muestra:
            - Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
            - Solo los valores del canal azul para todos los píxeles de la imagen.
            - Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`).
- 
    
    Calcular la distancia euclidiana entre dos puntos en un espacio de 5 dimensiones.
    
    ### Tareas:
    
    - Crea dos puntos en un espacio de 5 dimensiones como arrays de NumPy. Los puntos serán:
        - **Punto 1**: (2,3,5,7,11)
            
            (2,3,5,7,11)
            
        - **Punto 2**: (1,4,6,8,10)
            
            (1,4,6,8,10)
            
    - Utiliza la función `np.linalg.norm()` para calcular la distancia entre estos dos puntos en 5 dimensiones.
    - Imprime el resultado de la distancia."""

# Generamos un array 3D de tamaño 4x4x3 con valores aleatorios entre 0 y 255
# Simula una imagen RGB donde cada píxel tiene valores para los canales R, G y B
imagen = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)
print("Array 3D que representa la imagen RGB:")
print(imagen)

# --- Tarea 2: Indexación en el array 3D ---

# Extraemos el primer píxel [0,0] con sus valores RGB
primer_pixel = imagen[0, 0, :]
print("\nPrimer píxel (posición [0,0]):", primer_pixel)

# Extraemos el último píxel [-1,-1] con sus valores RGB
ultimo_pixel = imagen[-1, -1, :]
print("Último píxel (posición [-1,-1]):", ultimo_pixel)

# Extraemos el valor del canal rojo del píxel en la segunda fila y tercera columna
valor_rojo = imagen[1, 2, 0]  # Canal rojo es el índice 0
print("Valor del canal rojo del píxel en [1,2]:", valor_rojo)

# --- Tarea 3: Slicing en el array 3D ---

# Extraemos toda la primera fila (todos los píxeles y sus valores RGB)
primera_fila = imagen[0, :, :]
print("\nPrimera fila completa con valores RGB:")
print(primera_fila)

# Extraemos solo los valores del canal azul para todos los píxeles
canal_azul = imagen[:, :, 2]  # Canal azul es el índice 2
print("\nValores del canal azul para todos los píxeles:")
print(canal_azul)

# Extraemos un recorte central de la imagen (filas y columnas intermedias)
recorte_central = imagen[1:3, 1:3, :]  # Seleccionamos un subarray
print("\nRecorte central de la imagen (posiciones [1:3, 1:3]):")
print(recorte_central)




In [ ]:
"""- 5. Distancia euclidiana con fórmula optimizada
    
    Calcular la distancia euclidiana entre dos puntos en un espacio de 5 dimensiones.
    
    ### Tareas:
    
    - Crea dos puntos en un espacio de 5 dimensiones como arrays de NumPy. Los puntos serán:
        - **Punto 1**: (2,3,5,7,11)
            
            (2,3,5,7,11)
            
        - **Punto 2**: (1,4,6,8,10)
            
            (1,4,6,8,10)
            
    - Utiliza la función np.linalg.norm() para calcular la distancia entre estos dos puntos en 5 dimensiones.
    - Imprime el resultado de la distancia."""


# Creamos los dos puntos como arrays de NumPy
punto_1 = np.array([2, 3, 5, 7, 11])
punto_2 = np.array([1, 4, 6, 8, 10])

# Calculamos la distancia euclidiana utilizando np.linalg.norm()
distancia = np.linalg.norm(punto_1 - punto_2)

# Mostramos el resultado
print("Distancia euclidiana entre los puntos:", distancia)



In [12]:
import numpy as np
"""- 6. Análisis del rendimiento académico utilizando normas L1 y L2
    
    Eres un analista educativo y debes evaluar el rendimiento de un grupo de estudiantes en varias asignaturas. Dispones de una matriz con las calificaciones obtenidas por cada estudiante en distintas materias. Para analizar los datos, se te pide:
    
    ### Tareas:
    
    - **Calcular la norma L1 y la norma L2** de las calificaciones de cada estudiante para medir la dispersión y la magnitud de sus puntuaciones.
    - **Calcular la norma L1 y la norma L2** para cada asignatura para entender lo variadas que son las calificaciones en cada materia.
    - **Utilizar `axis=1`** para obtener las puntuaciones totales de cada estudiante (sumando todas las asignaturas).
    - **Utilizar `axis=0`** para obtener las puntuaciones totales de cada asignatura (sumando las calificaciones de todos los alumnos).
    - **Aplicar `keepdims=True`** para mantener la estructura de la matriz al realizar las operaciones y evitar problemas de dimensión."""

    #Datos de entrada
calificaciones = np.array([
    [88, 78, 64, 92, 57, 70, 88, 68, 72, 60],
    [60, 73, 85, 89, 73, 52, 71, 51, 73, 93],
    [79, 87, 51, 70, 82, 61, 71, 93, 74, 98],
    [76, 91, 77, 65, 64, 96, 93, 52, 86, 56],
    [70, 58, 88, 67, 53, 74, 63, 99, 58, 75],
    [82, 79, 91, 88, 66, 78, 79, 63, 59, 89],
    [56, 66, 73, 77, 75, 80, 70, 64, 88, 60],
    [80, 62, 79, 85, 92, 72, 80, 69, 78, 66],
    [88, 90, 69, 77, 66, 72, 65, 73, 92, 81],
    [60, 80, 69, 94, 81, 88, 93, 60, 58, 79],
    [78, 72, 74, 81, 67, 93, 60, 72, 85, 92],
    [86, 90, 70, 64, 93, 58, 61, 95, 79, 84],
    [85, 77, 91, 85, 61, 63, 58, 68, 65, 90],
    [71, 79, 69, 58, 75, 78, 62, 82, 77, 59],
    [87, 76, 72, 68, 88, 65, 75, 90, 69, 79],
    [78, 71, 94, 67, 72, 88, 58, 79, 91, 67],
    [67, 64, 85, 81, 70, 84, 79, 73, 62, 77],
    [90, 61, 60, 91, 72, 89, 77, 75, 76, 83],
    [94, 83, 80, 59, 65, 75, 63, 92, 68, 60],
    [80, 81, 68, 95, 72, 93, 89, 59, 81, 85],
    [88, 63, 90, 77, 69, 72, 85, 78, 61, 93],
    [91, 65, 79, 92, 63, 74, 87, 70, 92, 85],
    [92, 80, 76, 72, 81, 87, 64, 74, 70, 67],
    [72, 83, 91, 58, 67, 88, 81, 76, 74, 92],
    [84, 91, 81, 77, 80, 63, 70, 79, 89, 65],
    [66, 65, 77, 58, 79, 61, 86, 72, 64, 74],
    [94, 74, 83, 89, 77, 68, 81, 92, 70, 68],
    [73, 72, 82, 80, 79, 64, 69, 60, 76, 79],
    [82, 79, 75, 89, 85, 81, 62, 64, 60, 92],
    [87, 88, 80, 74, 85, 90, 75, 68, 68, 71],
    [81, 79, 85, 76, 64, 85, 71, 77, 67, 93],
    [82, 89, 77, 72, 66, 84, 92, 60, 67, 65],
    [90, 63, 94, 67, 88, 93, 79, 64, 88, 80],
    [81, 90, 72, 76, 74, 93, 88, 84, 80, 65],
    [86, 75, 67, 81, 93, 79, 91, 64, 78, 74],
    [69, 85, 90, 91, 60, 76, 84, 78, 74, 64],
    [67, 91, 94, 78, 81, 73, 62, 67, 60, 92],
    [85, 79, 73, 60, 85, 90, 82, 75, 74, 68],
    [91, 83, 77, 92, 74, 68, 64, 92, 90, 92],
    [65, 93, 88, 82, 92, 67, 79, 68, 81, 93],
    [92, 79, 90, 92, 72, 80, 61, 75, 86, 90],
    [80, 67, 76, 84, 92, 90, 79, 93, 74, 88],
    [60, 79, 90, 93, 64, 61, 85, 76, 92, 72],
    [88, 67, 72, 64, 80, 90, 79, 75, 85, 81],
    [79, 92, 75, 72, 92, 81, 79, 70, 68, 68],
    [65, 60, 79, 89, 79, 82, 86, 64, 60, 81],
    [92, 81, 60, 79, 94, 78, 80, 91, 85, 68],
    [79, 64, 81, 72, 68, 75, 80, 94, 79, 61],
    [79, 94, 64, 89, 80, 85, 74, 82, 65, 91]
])
"""- ¿Por qué la norma L1 representa la suma absoluta de las calificaciones?
- ¿Por qué la norma L2 nos da una idea de la magnitud total de los valores, penalizando más las notas altas?
- ¿Cómo afecta `keepdims=True` en las operaciones realizadas?"""


"""- **Calcular la norma L1 y la norma L2** de las calificaciones de cada estudiante para medir la dispersión y la magnitud de sus puntuaciones.
    - **Calcular la norma L1 y la norma L2** para cada asignatura para entender lo variadas que son las calificaciones en cada materia."""
# Norma L1 para cada estudiante, axis 1 para calcular los estudiantes que es cada fila
norma_L1_estudiantes = np.linalg.norm(calificaciones, ord=1, axis=1, keepdims=True)

# Norma L2 para cada estudiante, 
norma_L2_estudiantes = np.linalg.norm(calificaciones, ord=2, axis=1, keepdims=True)

# Norma L1 para cada asignatura, axis=0 porque las columnas representan las asignaturas, y queremos realizar el cálculo columna por columna
norma_L1_asignaturas = np.linalg.norm(calificaciones, ord=1, axis=0, keepdims=True)

# Norma L2 para cada asignatura
norma_L2_asignaturas = np.linalg.norm(calificaciones, ord=2, axis=0, keepdims=True)

# uma total por estudiante
total_estudiantes = np.sum(calificaciones, axis=1, keepdims=True)

# Suma total por asignatura
total_asignaturas = np.sum(calificaciones, axis=0, keepdims=True)

"""print("L1 de los estudiantes: ",norma_L1_estudiantes)
print("L2 de los estudiantes: ",norma_L2_estudiantes)
print("L1 de las asignaturas: ",norma_L1_asignaturas)
print("L2 de las asignaturas: ",norma_L2_asignaturas)"""
print("Puntuaciones totales por estudiante:\n", total_estudiantes)
print("Puntuaciones totales por asignatura:\n", total_asignaturas)



Puntuaciones totales por estudiante:
 [[737]
 [720]
 [766]
 [756]
 [705]
 [774]
 [709]
 [763]
 [773]
 [762]
 [774]
 [780]
 [743]
 [710]
 [769]
 [765]
 [742]
 [774]
 [739]
 [803]
 [776]
 [798]
 [763]
 [782]
 [779]
 [702]
 [796]
 [734]
 [769]
 [786]
 [778]
 [754]
 [806]
 [803]
 [788]
 [771]
 [765]
 [771]
 [823]
 [808]
 [817]
 [823]
 [772]
 [781]
 [776]
 [745]
 [808]
 [753]
 [803]]
Puntuaciones totales por asignatura:
 [[3895 3788 3827 3828 3707 3807 3710 3659 3668 3805]]


In [6]:
"""- 7. Producto cruzado para calcular variaciones en la ruta de un avión
    
    **Contexto:**
    
    Una compañía aérea está analizando la trayectoria de sus aviones para garantizar que mantienen el rumbo adecuado. En particular, necesitan calcular la dirección perpendicular a la ruta de vuelo cuando hay desviaciones debido a corrientes de aire. Para ello, utilizarán el **producto cruzado** de dos vectores:
    
    1. **Vector de vuelo previsto:** Representa la trayectoria que el avión debería seguir.
    2. **Vector de vuelo real:** Representa la trayectoria que el avión está siguiendo en realidad.
    
    El producto cruzado entre estos dos vectores proporciona un tercer vector que indica la dirección de la desviación en el espacio tridimensional.
    
    ---
    
    ### **Enunciado del Ejercicio**
    
    Dado un avión que vuela en el espacio tridimensional, representaremos su trayectoria mediante vectores en un sistema de coordenadas cartesianas.
    
    1. Define los siguientes vectores en NumPy:
        - **Vector de vuelo previsto**: `v1 = [3, 4, 0]`
        - **Vector de vuelo real**: `v2 = [4, 3, 1]`
    2. Calcula el **producto cruzado** entre `v1` y `v2` utilizando NumPy.
    3. Interpreta el resultado:
        - ¿En qué dirección ocurre la desviación?
        - ¿Cómo se podría corregir la trayectoria del avión basándonos en este cálculo?
    
    ---
    
    ### **Explicación**
    
    - El producto cruzado entre dos vectores en el espacio tridimensional genera un tercer vector **perpendicular** al plano que forman los dos vectores originales.
    - En este caso, el vector resultante indica la dirección en la que el avión está siendo desviado.
    - Si el resultado es `[x, y, z]`, la desviación se produce en la dirección del eje **z**, lo que significa que el avión está cambiando de altitud en lugar de mantenerse en el plano original.
    
    **Desafío Extra:**
    
    - Modifica el vector `v2` y observa cómo cambia la desviación.
    - ¿Cómo cambiaría el resultado si el avión volara completamente en un plano 2D (sin componente en `z`)?"""

# Vectores, 1 el vuelo previsto y 2 el vuelo real
v1 = np.array([3, 4, 0]) 
v2 = np.array([4, 3, 1])  

# Producto cruzado
cruz = np.cross(v1, v2)


print("Vector de vuelo previsto v1:", v1)
print("Vector de vuelo real v2:", v2)
print("Producto cruzado entre v1 y v2:", cruz)

# Interpretación
if cruz[2] != 0:
    print(f"La desviación ocurre fuera del plano original, con componente z = {cruz[2]}.")
else:
    print("La desviación ocurre únicamente en el plano horizontal.")
# El producto cruzado nos da la dirección perpendicular a la trayectoria del avión

"""Si el resultado es [x, y, z] la desviación se produce en la dirección del eje z que significa que el avión está cambiando de altitud en lugar de mantenerse en el plano original. En este caso, la desviación ocurre en la dirección del eje z. Para corregir la trayectoria del avión, se podría ajustar la velocidad o la dirección del avión para compensar la desviación"""



Vector de vuelo previsto (v1): [3 4 0]
Vector de vuelo real (v2): [4 3 1]
Producto cruzado entre v1 y v2: [ 4 -3 -7]
La desviación ocurre fuera del plano original, con componente z = -7.


In [ ]:
"""- 8. Análisis del rendimiento de un atleta con producto escalar
    
    ### **Contexto**
    
    Eres un entrenador de atletismo y necesitas evaluar el desempeño de un atleta en diferentes pruebas de velocidad y resistencia. Para hacerlo, utilizas dos vectores:
    
    - **Vector de rendimiento del atleta:** Contiene los tiempos que ha tardado en recorrer diferentes distancias (100m, 200m, 400m, 800m, 1500m).
    - **Vector de importancia de cada prueba:** Define qué tan importante es cada distancia en la evaluación final (por ejemplo, si priorizas pruebas de velocidad o de resistencia).
    
    El **producto escalar** te permitirá calcular un **índice de rendimiento** que refleja la eficiencia del atleta considerando la importancia de cada prueba.
    
    ### **Objetivos del ejercicio**
    
    1. Representar el rendimiento de un atleta y la importancia de cada prueba como vectores.
    2. Calcular el producto escalar entre ambos vectores.
    3. Interpretar el resultado: un menor valor indica mejor rendimiento, ya que los tiempos son menores en pruebas más importantes.
    
    ### **Datos de entrada**
    
    Supongamos que tenemos los siguientes datos:
    
    - **Tiempos del atleta (en segundos):** `[11, 22, 50, 110, 250]`
    - **Importancia de las pruebas:** `[0.4, 0.3, 0.2, 0.1, 0.05]` *(priorizamos más las pruebas cortas de velocidad que las largas de resistencia).*
    
    ### **Tareas**
    
    1. Representa los datos como vectores en NumPy.
    2. Calcula el producto escalar entre los vectores.
    3. Explica qué significa el resultado obtenido en términos del rendimiento del atleta.
    
    ### Preguntas
    
    - ¿Cómo afectaría al resultado si el atleta mejora su tiempo en la prueba de 100m?
    - ¿Qué pasaría si le damos más importancia a las pruebas de resistencia?
    - ¿Cómo se podría utilizar esta métrica para comparar a diferentes atletas?"""


# Definimos los tiempos del atleta en segundos para cada prueba:
# 100m, 200m, 400m, 800m, 1500m
tiempos = np.array([11, 22, 50, 110, 250])

# Definimos la importancia de cada prueba como un vector. 
# Los valores reflejan cuánto peso le damos a cada distancia (las más cortas son más importantes).
# Nota: Los valores suman 1 porque están normalizados.
importancia = np.array([0.4, 0.3, 0.2, 0.1, 0.05])

# --- Cálculo del índice de rendimiento ---

# Calculamos el producto escalar entre los tiempos y la importancia.
# Esto nos dará un índice que combina ambos vectores según la importancia relativa de cada prueba.
indice_rendimiento = np.dot(tiempos, importancia)

# Mostramos el índice de rendimiento del atleta.
# Un valor menor indica que el atleta tuvo mejores tiempos en las pruebas más importantes.
print("Índice de rendimiento del atleta:", indice_rendimiento)

# --- Análisis de escenarios alternativos ---

# Escenario (a): Mejoramos el tiempo del atleta en los 100m.
# Suponemos que baja su tiempo de 11 a 10 segundos.

# Creamos una copia del vector original de tiempos para modificarlo sin afectar los datos iniciales.
tiempos_mejorados = tiempos.copy()
# Cambiamos el tiempo en los 100m (posición 0 del vector).
tiempos_mejorados[0] = 10

# Calculamos el nuevo índice de rendimiento con los tiempos mejorados.
indice_rendimiento_mejorado = np.dot(tiempos_mejorados, importancia)
print("Índice de rendimiento tras mejorar los 100m:", indice_rendimiento_mejorado)

# Escenario (b): Cambiamos la importancia para priorizar las pruebas de resistencia.
# Modificamos el vector de importancia para darle más peso a las distancias largas.
importancia_resistencia = np.array([0.1, 0.1, 0.2, 0.3, 0.3])  # Más peso a pruebas largas

# Calculamos el índice de rendimiento con las nuevas prioridades.
indice_rendimiento_resistencia = np.dot(tiempos, importancia_resistencia)
print("Índice de rendimiento priorizando resistencia:", indice_rendimiento_resistencia)

# Escenario (c): Comparamos el rendimiento con otro atleta.
# Definimos los tiempos de un segundo atleta para las mismas pruebas.
tiempos_otro_atleta = np.array([12, 21, 45, 100, 240])

# Calculamos el índice de rendimiento del otro atleta usando el mismo vector de importancia.
indice_otro = np.dot(tiempos_otro_atleta, importancia)
print("Índice de rendimiento del otro atleta:", indice_otro)

# Comparamos los índices de ambos atletas.
# El atleta con el índice más bajo tiene mejor rendimiento.
if indice_rendimiento < indice_otro:
    print("El primer atleta tiene un mejor rendimiento.")
else:
    print("El segundo atleta tiene un mejor rendimiento.")


In [ ]:
"""- 9. Normalización de datos con la norma L2 en rendimiento deportivo
    
    ### **Contexto**
    
    Eres un analista de rendimiento deportivo y tienes un equipo de **fútbol** que ha jugado **una temporada completa**. Para evaluar a cada jugador, has recopilado sus estadísticas en diferentes categorías:
    
    - **Goles marcados**
    - **Asistencias**
    - **Pases completados**
    - **Regates exitosos**
    - **Tiros a puerta**
    
    Sin embargo, los valores en cada categoría tienen escalas diferentes, por lo que es difícil comparar directamente el desempeño de los jugadores. Para resolver este problema, aplicarás la **normalización con la norma L2**, lo que permitirá convertir todas las estadísticas a una escala comparable.
    
    ### **Objetivo del ejercicio**
    
    1. Representar el rendimiento de los jugadores como una matriz en NumPy.
    2. Aplicar la **normalización L2** a cada jugador para escalar sus valores entre 0 y 1 mientras se mantiene la proporción relativa.
    3. Comparar los jugadores después de la normalización.
    
    ### **Datos de entrada**
    
    Supongamos que tenemos los datos de 5 jugadores:
    
    | Jugador | Goles | Asistencias | Pases | Regates | Tiros a puerta |
    | --- | --- | --- | --- | --- | --- |
    | Jugador 1 | 10 | 7 | 300 | 25 | 40 |
    | Jugador 2 | 15 | 10 | 250 | 30 | 50 |
    | Jugador 3 | 5 | 12 | 280 | 20 | 35 |
    | Jugador 4 | 8 | 6 | 310 | 15 | 38 |
    | Jugador 5 | 12 | 9 | 270 | 28 | 45 |
    
    Cada jugador es un **vector** con 5 componentes. Aplicaremos la **norma L2** para normalizar sus estadísticas.
    
    ### **Tareas**
    
    1. Representar los datos como una matriz en NumPy.
    2. Aplicar la normalización L2 a cada jugador (por filas, usando `axis=1`).
    3. Mostrar los valores normalizados y analizar cómo se comparan los jugadores tras la normalización.
    
    ### Preguntas
    
    - ¿Cómo cambian los valores después de la normalización?
    - ¿Por qué la normalización L2 es útil cuando los datos tienen escalas diferentes?
    - ¿Qué pasaría si normalizamos por **columnas (axis=0)** en lugar de por filas?"""


# Importamos NumPy para manejar los datos y realizar operaciones matemáticas.
import numpy as np

# --- Representación de los datos como una matriz ---

# Creamos una matriz en la que cada fila representa a un jugador
# y cada columna corresponde a una estadística específica (goles, asistencias, etc.).
datos = np.array([
    [10, 7, 300, 25, 40],  # Jugador 1
    [15, 10, 250, 30, 50],  # Jugador 2
    [5, 12, 280, 20, 35],   # Jugador 3
    [8, 6, 310, 15, 38],    # Jugador 4
    [12, 9, 270, 28, 45]    # Jugador 5
])

# --- Normalización L2 por filas (jugadores) ---

# Calculamos la norma L2 para cada fila (jugador).
# La norma L2 es la raíz cuadrada de la suma de los cuadrados de los valores de la fila.
normas = np.linalg.norm(datos, axis=1, keepdims=True)

# Normalizamos dividiendo cada valor por la norma correspondiente.
# Esto escala los valores de cada jugador manteniendo la proporción relativa.
datos_normalizados = datos / normas

# Mostramos la matriz normalizada.
print("Estadísticas normalizadas (por filas):")
print(datos_normalizados)

# --- Análisis de los resultados ---

# Explicación del cambio:
# Los valores ahora están en una escala comparable (entre 0 y 1).
# Los jugadores con mayores estadísticas totales tendrán vectores con valores más homogéneos.

# --- Escenario alternativo: Normalización por columnas (estadísticas) ---

# Calculamos la norma L2 por columnas para ver cómo cambian los datos.
# Esto normaliza cada estadística entre los jugadores, en lugar de normalizar por jugador.
normas_columnas = np.linalg.norm(datos, axis=0, keepdims=True)
datos_normalizados_columnas = datos / normas_columnas

print("\nEstadísticas normalizadas (por columnas):")
print(datos_normalizados_columnas)

# --- Preguntas y respuestas ---

# Pregunta 1: ¿Cómo cambian los valores después de la normalización?
# Respuesta: Después de la normalización L2 por filas, cada fila tiene una norma igual a 1.
# Esto significa que las estadísticas de cada jugador son escaladas proporcionalmente, 
# permitiendo compararlas en igualdad de condiciones, independientemente de las escalas originales.

# Pregunta 2: ¿Por qué la normalización L2 es útil cuando los datos tienen escalas diferentes?
# Respuesta: Es útil porque algunas estadísticas, como los pases (escala de cientos), tienen valores mucho mayores
# que otras, como los goles o asistencias. Sin normalización, los valores grandes dominarían cualquier análisis.
# La normalización L2 iguala la influencia de todas las características.

# Pregunta 3: ¿Qué pasa si normalizamos por columnas (axis=0)?
# Respuesta: Normalizar por columnas iguala la importancia relativa de cada estadística entre los jugadores.
# Esto sería útil si queremos comparar cómo se desempeñan los jugadores en relación con el grupo,
# en lugar de analizar cada jugador de manera independiente.


